### ISSUE TITLE
Započeti razvoj Web Backenda

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#18]
Započeti razvoj Web Backenda na instaliranom git serveru.

**Comment by MaNemoj01** [comment]
<img width="1338" alt="Screen Shot 2021-04-28 at 23 29 09" src="https://user-images.githubusercontent.com/44163914/116475076-9fc61480-a879-11eb-8ab9-d680a3a709b6.png">

Server je up and running. Tretnuno je nesto sitno implementirano sa testovima da provjerim da li ce se na Jenskinsu sve kako treba pokrenuti i jeste.
Pristup se server moze tako se se pucaju zahtjevi na:
http://34.65.120.82:23456/

Trenuto na tom kad se odradi get dobije se template html da je stranica u izradi, poslije kad popunim postman proslijedt cu vam endpointe radi lakseg developmenta i vama i meni.


<img width="1440" alt="Screen Shot 2021-04-28 at 23 32 43" src="https://user-images.githubusercontent.com/44163914/116475366-0ba87d00-a87a-11eb-8e74-f8c5ab10fbb7.png">
