### ISSUE TITLE
Doraditi pipeline build na Jenkinsu

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#27]
Opis zadatka:   
- Doraditi pipeline build na Jenkinsu koji je kreiran u PZ6 tako da se vrši deployment frontend i backend aplikacije u dva različita docker kontejnera.

**Comment by MaNemoj01** [comment]
Gotovo nakon mnogo tries and errors gotovo je. Kasnim jer nam sever nije bio u funkcionalnom stanju proslu sedmicu

**Comment by MaNemoj01** [comment]
![image](https://user-images.githubusercontent.com/44163914/118718118-2e99d180-b827-11eb-9614-a53a3192bf08.png)
