### ISSUE TITLE
Podešavanje domene i nginx-a

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#28]
Opis zadatka:   
- Kreiranje vlastite internet poddomene na nekom od servisa koji nude besplatne poddomene, kao što je hopto.org i povezivanje iste sa serverom.   
- Instaliranje i podešavanje nginx reverznog proxy-ja tako da su različiti servisi dostupni preko URLova na baznoj domeni npr. mojadomena.hopto.org/jenkins.   
- Podešavanje firewalla tako da se više ne može pristupiti servisima direktno preko porta nego isključivo kroz nginx.

**Comment by MaNemoj01** [comment]
Podesena je domena a domena je 

[http://tehnicki-pregled.hopto.org/](http://tehnicki-pregled.hopto.org/)


Obrisani su firewall portovi za podešene stvari ispod.
Podešeni su  reverse proxy za:

Frontend
[http://tehnicki-pregled.hopto.org/](http://tehnicki-pregled.hopto.org/)

Backend pomoću ruta:
[http://tehnicki-pregled.hopto.org/api/v1](http://tehnicki-pregled.hopto.org/api/v1)

Jenkins
[http://tehnicki-pregled.hopto.org/jenkins](http://tehnicki-pregled.hopto.org/jenkins)

Gitea
[http://tehnicki-pregled.hopto.org/gitea](http://tehnicki-pregled.hopto.org/gitea)

Jasper Server
[http://tehnicki-pregled.hopto.org/jasperserver/](http://tehnicki-pregled.hopto.org/jasperserver/)

**Comment by MaNemoj01** [comment]
Prikaz pristupa endpointima nakon postavljanja nginx i domene

![image](https://user-images.githubusercontent.com/44163914/119263216-6cf40f80-bbde-11eb-9751-c39d123a11dd.png)
