### ISSUE TITLE
Razvoj backenda

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#31]
- Prepravljanje korisnika i CRUD-a, te kreiranje posebne rute za administatorsko kreiranje korisnika (tehničara i administratora)
-  Kreiranje rute za getanje svih korisnika sistema

**Comment by MaNemoj01** [comment]
Gotovo i napravljen je Open Api na StopLight radi lakseg pregleda Api dokumentacije za vas daljnji razvoj aplikacije.

https://tpv-nrs.stoplight.io/docs/tehnicki-pregled-vozila-nrs/reference/Users.json

Ispod se nalazi klip sa kratkim pregled kako se koristi StopLight.

https://user-images.githubusercontent.com/44163914/118743141-125f5a00-b852-11eb-95c4-c5427e30d104.mov
