### ISSUE TITLE
CRUD tehnički pregled

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#32]
- Kreiranje CRUD-a za tehnički pregled vozila

**Comment by MaNemoj01** [comment]
Svi endpointi se nalaze na linku:

https://tpv-nrs.stoplight.io/docs/tehnicki-pregled-vozila-nrs/reference/Exams.json

Za sve dodatne endpointe po potrebama se mozemo dogovoriti na buducim sastancima.
Izmjene postojecih endpointa isto se mozemo dogovoriti da namjestim da vam odgovora po vasih potrebama.
