### ISSUE TITLE
Prepraviti ograničenja

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#4]
Opis zadatka:
-  Konsultovati relevantnu zakonsku regulativu i pravila
- U poglavlju Ograničenja (2.4) navesti zakonsku regulativu koja diktira kako se sistem treba razvijati, kao i druge vrste ograničenja.

**Comment by MaNemoj01** [comment]
Uradeno. Konsultovano sa pravilnikom koji je sacinjen od sluzbenih glasnika ispod: 

- („Službeni glasnik BiH“, broj 13/07)
- („Službeni glasnik BiH“, broj 72/07)
- („Službeni glasnik BiH“, broj 74/08)
- („Službeni glasnik BiH“, broj 3/09)
- („Službeni glasnik BiH“, broj: 76/09)
- („Službeni glasnik BiH“, broj: 29/11)

**Comment by MaNemoj01** [comment]
Uradeno. Konsultovano sa pravilnikom koji je sacinjen od sluzbenih glasnika ispod:

- („Službeni glasnik BiH“, broj 13/07)
- („Službeni glasnik BiH“, broj 72/07)
- („Službeni glasnik BiH“, broj 74/08)
- („Službeni glasnik BiH“, broj 3/09)
- („Službeni glasnik BiH“, broj: 76/09)
- („Službeni glasnik BiH“, broj: 29/11)
