### ISSUE TITLE
Kreiranje cloud host-a

### ISSUE THREAD

**Issue by amirakurtagic1** [amirakurtagic1/nrs20-tim2#5]
Opis zadatka:   

- Potrebno je kreirati cloud host sa nekom od poznatijih Linux distribucija i root pristupom

**Comment by MaNemoj01** [comment]
Za cloud hosting odabran je Heroku, pa kao jedan od prvih koraka jeste da sam napravio GitHub repozitorij za BE server, i otkucao osnovni server na koji ću nadograđivati dalje. Za server je odabran da bude NodeJS, pomoću njega serviram public folder sa servera sto će kolega Emir izbildati svoj web aplikaciju i na taj način ćemo servirati i BE server i FE web aplikaciju.

Servirana BE i FE aplikacija se nalaze na url: https://tehnicki-pregled.herokuapp.com/
Sad za sad za FE web aplikaciju se servira html template a mjesto njega će da dođe web aplikacija koju će kolega Emir razviti.
